# Generated by Django 5.2.10 on 2026-03-11 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0002_alter_batch_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(editable=False, max_length=100)),
                ('last_name', models.CharField(editable=False, max_length=100)),
                ('starting_semester', models.CharField(editable=False, max_length=50)),
                ('concluding_semester', models.CharField(blank=True, max_length=50, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('current_professional_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_sector', models.CharField(blank=True, choices=[('Private', 'Private'), ('Corporate', 'Corporate'), ('Government', 'Government'), ('NGO', 'NGO'), ('INGO', 'INGO'), ('Entrepreneur', 'Entrepreneur'), ('Performance_Art', 'Performance Art'), ('Other', 'Other')], max_length=20, null=True)),
                ('primary_education', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_education', models.CharField(blank=True, max_length=255, null=True)),
                ('higher_secondary_education', models.CharField(blank=True, max_length=255, null=True)),
                ('tertiary_education', models.CharField(blank=True, max_length=255, null=True)),
                ('current_country_of_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Other', 'Other')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_record', to='batches.student')),
            ],
        ),
    ]
