# Generated by Django 5.2.10 on 2026-03-11 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnirecord',
            name='higher_secondary_education',
        ),
        migrations.RemoveField(
            model_name='alumnirecord',
            name='primary_education',
        ),
        migrations.RemoveField(
            model_name='alumnirecord',
            name='secondary_education',
        ),
        migrations.RemoveField(
            model_name='alumnirecord',
            name='tertiary_education',
        ),
        migrations.AddField(
            model_name='alumnirecord',
            name='professional_sector_sub_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='FurtherEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Post-graduate', 'Post-graduate')], max_length=50)),
                ('degree_name', models.CharField(max_length=255)),
                ('program_name', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=50)),
                ('start_year', models.IntegerField()),
                ('graduation_year', models.IntegerField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='further_educations', to='alumni.alumnirecord')),
            ],
            options={
                'ordering': ['-graduation_year'],
            },
        ),
    ]
