# Generated by Django 5.2.10 on 2026-01-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='program',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='year',
        ),
    ]
