# Generated by Django 5.2.10 on 2026-01-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_config', '0002_remove_cohort_program_remove_cohort_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_config.cohort')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_config.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_config.semester')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_config.academicyear')),
            ],
            options={
                'unique_together': {('program', 'semester', 'year', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('degree_choice', models.CharField(choices=[('M.Sc', 'M.Sc'), ('PgD', 'PgD'), ('M.ED', 'M.ED')], max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Graduated', 'Graduated')], default='Active', max_length=15)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='batches.batch')),
            ],
        ),
    ]
